In [14]:
import numpy as np
import pandas as pd 
%matplotlib inline
# np.set_printoptions(threshold=np.inf)
import datetime
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from scipy.stats import zscore
from imblearn.over_sampling import SMOTE
from scipy.stats import itemfreq
# from sklearn.decomposition import PCA
from time import time

In [15]:
def createSubmission(filename, y):
    fo = open( filename , 'w' )
    fo.write("ImageId,PredictedClass\n")
    for i in range(y.shape[0]):
        fo.write(str(i)+","+str(y[i])+"\n")
    fo.close()

def nnPredict(model,x, y):
    ypredict= model.predict(x)
    score= f1_score(y , ypredict, average='macro');
    return score

In [3]:
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
xout= np.load("./X_test.npy")

In [16]:
#scale data
def normalize(x):
    r=zscore(x, axis=0)
    return r

In [4]:
def underSampling(x, y):
    cc = ClusterCentroids()
    x_resampled, y_resampled = cc.fit_sample(x, y)
    return (x_resampled, y_resampled)

In [5]:
#split dataset and normalization 
x_train, x_test, y_train, y_test = train_test_split(
    xin, yin, test_size=0.3, random_state=0)

#print(stats.itemfreq(y_train))
#print(stats.itemfreq(y_test))

x_train= normalize(x_train)
x_test= normalize(x_test)

#x_train, y_train = underSampling(x_train, y_train)

In [ ]:
nn = MLPClassifier(hidden_layer_sizes=(1851, 400,),
                   activation= 'tanh',
                   solver= 'lbfgs',
                   alpha= 0.05,
                   max_iter= 500,
                   learning_rate_init= 0.001,
                   verbose= True,
                   early_stopping= True,
                   validation_fraction= 0.3,
                   tol= 0.0001
                  )

nn.fit(x_train,y_train)
y_p= nn.predict(x_train)
print('Performance in sample:\n')
print(confusion_matrix(y_train, y_p))
print()
print(f1_score(y_train, y_p, average= None))
print()
y_pred = nn.predict(x_test)
print("Detailed classification report:")
print()
print(confusion_matrix(y_test, y_pred))
print()
print(f1_score(y_test, y_pred, average= None))
print()
score= nnPredict(nn, x_test, y_test)
print("F1 _macro:" + str(score))

In [8]:
nn = MLPClassifier(hidden_layer_sizes=(1851, 400,),
                   activation= 'tanh',
                   solver= 'lbfgs',
                   alpha= 1,
                   max_iter= 500,
                   learning_rate_init= 0.001,
                   verbose= True,
                   early_stopping= True,
                   validation_fraction= 0.3,
                   tol= 0.0001
                  )

nn.fit(x_train,y_train)
y_p= nn.predict(x_train)
print('Performance in sample:\n')
print(confusion_matrix(y_train, y_p))
print()
print(f1_score(y_train, y_p, average= None))
print()
y_pred = nn.predict(x_test)
print("Detailed classification report:")
print()
print(confusion_matrix(y_test, y_pred))
print()
print(f1_score(y_test, y_pred, average= None))
print()
score= nnPredict(nn, x_test, y_test)
print("F1 _macro:" + str(score))

Performance in sample:

[[ 34   0   0   0   0   0   0]
 [  0 136   0   0   0   0   0]
 [  0   0  57   0   0   0   0]
 [  0   0   0 277   0   0   0]
 [  0   0   0   0  62   0   0]
 [  0   0   0   0   0  44   0]
 [  0   0   0   0   0   0  66]]

[ 1.  1.  1.  1.  1.  1.  1.]

Detailed classification report:

[[  9   6   1   0   0   0   1]
 [  3  35   2   5   0   2   0]
 [  0   2  23   3   0   0   0]
 [  1   2   0 111   1   1   2]
 [  0   1   1   0  19   1   2]
 [  0   0   0   2   3  11   0]
 [  0   1   2   3   1   0  33]]

[ 0.6         0.74468085  0.80701754  0.91735537  0.79166667  0.70967742
  0.84615385]

F1 _macro:0.773793099857


In [ ]:
# alpha 5 0.783268274508 after decreasing? lr= 0.0001
# alpha 50 too high

# alpha = 20 -> F1 _macro:0.770553013578
# alpha = 5 lr= 0.01 -> 0.786858651364
# a = 7 lr= 0.01 -> 0.788296988937
# a=10 -> 0.774417948608
# a= 2 -> 0.780102477052
# a = 8.5 -> 0.774417948608
# a = 20 -> 0.770553013578
# a = 50 -> 0.73290899476
#a = 100 -> too bad 
# a= 0.5 -> 0.780339828822
# a = 7.5 -> 0.781181790173

In [10]:
nn = MLPClassifier(hidden_layer_sizes=(1851, 400,),
                   activation= 'tanh',
                   solver= 'lbfgs',
                   alpha= 1,
                   max_iter= 500,
                   learning_rate_init= 0.001,
                   verbose= True,
                   early_stopping= True,
                   validation_fraction= 0.3,
                   tol= 0.0001
                  )

nn.fit(x_train,y_train)
y_p= nn.predict(x_train)
print('Performance in sample:\n')
print(confusion_matrix(y_train, y_p))
print()
print(f1_score(y_train, y_p, average= None))
print()
y_pred = nn.predict(x_test)
print("Detailed classification report:")
print()
print(confusion_matrix(y_test, y_pred))
print()
print(f1_score(y_test, y_pred, average= None))
print()
score= nnPredict(nn, x_test, y_test)
print("F1 _macro:" + str(score))

Performance in sample:

[[ 34   0   0   0   0   0   0]
 [  0 136   0   0   0   0   0]
 [  0   0  57   0   0   0   0]
 [  0   0   0 277   0   0   0]
 [  0   0   0   0  62   0   0]
 [  0   0   0   0   0  44   0]
 [  0   0   0   0   0   0  66]]

[ 1.  1.  1.  1.  1.  1.  1.]

Detailed classification report:

[[  9   6   1   0   0   0   1]
 [  2  36   2   5   0   2   0]
 [  0   2  23   3   0   0   0]
 [  1   2   1 112   0   0   2]
 [  0   1   1   0  20   1   1]
 [  0   1   0   1   3  11   0]
 [  0   1   1   3   1   0  34]]

[ 0.62068966  0.75        0.80701754  0.92561983  0.83333333  0.73333333
  0.87179487]

F1 _macro:0.791684081743


In [32]:
def evaluateModel(alp):
    nn = MLPClassifier(hidden_layer_sizes=(1851, 400,),
                   activation= 'relu',
                   solver= 'lbfgs',
                   alpha= alp,
                   max_iter= 500,
                   learning_rate_init= 0.001,
                   verbose= True,
                   early_stopping= True,
                   validation_fraction= 0.3,
                   tol= 0.0001
                  )
    nn.fit(x_train,y_train)
    y_pred = nn.predict(x_test)
    matrix = confusion_matrix(y_test, y_pred)
    vect = f1_score(y_test, y_pred, average= None)
    score = nnPredict(nn, x_test, y_test)
    return (score, vect, matrix)

In [33]:
def overSampling(x, y, ki):
    sm = SMOTE(kind= ki)
    x_resampled, y_resampled = sm.fit_sample(x, y)
    return (x_resampled, y_resampled)

In [34]:
#run
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
x= xin
y= yin
ovr= 2
kind= 'svm'
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=0)
for _ in range(ovr):
    x_train,y_train = overSampling(x_train, y_train, kind)
print(x_train.shape)
print(x.shape)
print(itemfreq(yin))
print(itemfreq(y_train))

x_train= normalize(x_train)
x_test= normalize(x_test)

(901, 1850)
(966, 1850)
[[  0  51]
 [  1 183]
 [  2  85]
 [  3 395]
 [  4  86]
 [  5  60]
 [  6 106]]
[[  0 139]
 [  1 136]
 [  2  57]
 [  3 277]
 [  4  62]
 [  5 164]
 [  6  66]]


In [21]:
i = datetime.datetime.now()
tm= str(i.year) + '-' + str(i.month) + '-' + str(i.day) + '_' + str(i.hour) + '-' + str(i.minute)
filename = 'search'+ tm + 'ovr' + str(ovr)+'kind'+ kind +'.txt'
a= [0.001, 0.01, 1, 2, 3, 4, 5, 10, 20, 50]
t0= time()

fo = open( filename , 'w' )
fo.write(str(a))
fo.write('\n')
fo.write('hidden_layer_sizes=(1851, 400,), activation= tanh, solver= lbfgs,'+
         'alpha= alp,max_iter= 500,learning_rate_init= 0.001,'+
         'verbose= True, early_stopping= True, validation_fraction= 0.3, tol= 0.0001\n')
fo.close()

hscore= 0.0
lowestsc= 0.0
bestA= 0

for i in range(len(a)):
    score, vect, matrix= evaluateModel(a[i])
    fo = open( filename , 'a' )
    fo.write('\n')
    fo.write('For '+ str(a[i])+'\n')
    fo.write('Avg score '+ str(score)+'\n')
    fo.write('Score ' +str(vect)+'\n')
    fo.write('Conf matr'+'\n')
    fo.write(str(matrix))
    fo.write('\n')
    fo.close()
    
    if(score > hscore):
        worstPred= min(vect)
        if(worstPred > lowestsc):
            hscore= score
            lowestsc= worstPred
            bestA= a[i]

fo = open( filename , 'a' )
fo.write('Best a= '+ str(bestA)+'\n')
fo.write('Score = '+ str(hscore)+ '\n')
fo.write('Lowest score pred= '+ str(lowestsc)+'\n')
print('Best a= '+ str(bestA)+'\n')
print('Score = '+ str(hscore)+ '\n')
print('Done in ' + str(time()-t0)) 

Best a= 0.001

Score = 0.731525581495

Done in 1724.5113213062286


In [22]:
#run
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
x= xin
y= yin
ovr= 2
kind= 'regular'
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=0)
for _ in range(ovr):
    x_train,y_train = overSampling(x_train, y_train, kind)
print(x_train.shape)
print(x.shape)
print(itemfreq(yin))
print(itemfreq(y_train))

x_train= normalize(x_train)
x_test= normalize(x_test)

(1152, 1850)
(966, 1850)
[[  0  51]
 [  1 183]
 [  2  85]
 [  3 395]
 [  4  86]
 [  5  60]
 [  6 106]]
[[  0 277]
 [  1 136]
 [  2  57]
 [  3 277]
 [  4  62]
 [  5 277]
 [  6  66]]


In [23]:
i = datetime.datetime.now()
tm= str(i.year) + '-' + str(i.month) + '-' + str(i.day) + '_' + str(i.hour) + '-' + str(i.minute)
filename = 'search'+ tm + 'ovr' + str(ovr)+'kind'+ kind +'.txt'
a= [0.001, 0.01, 1, 2, 3, 4, 5, 10, 20, 50]
t0= time()

fo = open( filename , 'w' )
fo.write(str(a))
fo.write('\n')
fo.write('hidden_layer_sizes=(1851, 400,), activation= tanh, solver= lbfgs,'+
         'alpha= alp,max_iter= 500,learning_rate_init= 0.001,'+
         'verbose= True, early_stopping= True, validation_fraction= 0.3, tol= 0.0001\n')
fo.close()

hscore= 0.0
lowestsc= 0.0
bestA= 0

for i in range(len(a)):
    score, vect, matrix= evaluateModel(a[i])
    fo = open( filename , 'a' )
    fo.write('\n')
    fo.write('For '+ str(a[i])+'\n')
    fo.write('Avg score '+ str(score)+'\n')
    fo.write('Score ' +str(vect)+'\n')
    fo.write('Conf matr'+'\n')
    fo.write(str(matrix))
    fo.write('\n')
    fo.close()
    
    if(score > hscore):
        worstPred= min(vect)
        if(worstPred > lowestsc):
            hscore= score
            lowestsc= worstPred
            bestA= a[i]

fo = open( filename , 'a' )
fo.write('Best a= '+ str(bestA)+'\n')
fo.write('Score = '+ str(hscore)+ '\n')
fo.write('Lowest score pred= '+ str(lowestsc)+'\n')
print('Best a= '+ str(bestA)+'\n')
print('Score = '+ str(hscore)+ '\n')
print('Done in ' + str(time()-t0)) 

Best a= 2

Score = 0.744621928372

Done in 1768.3811700344086


In [35]:
#run
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
x= xin
y= yin
ovr= 1
kind= 'svm'
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=0)
for _ in range(ovr):
    x_train,y_train = overSampling(x_train, y_train, kind)
print(x_train.shape)
print(x.shape)
print(itemfreq(yin))
print(itemfreq(y_train))

x_train= normalize(x_train)
x_test= normalize(x_test)

(774, 1850)
(966, 1850)
[[  0  51]
 [  1 183]
 [  2  85]
 [  3 395]
 [  4  86]
 [  5  60]
 [  6 106]]
[[  0 132]
 [  1 136]
 [  2  57]
 [  3 277]
 [  4  62]
 [  5  44]
 [  6  66]]


In [37]:
i = datetime.datetime.now()
tm= str(i.year) + '-' + str(i.month) + '-' + str(i.day) + '_' + str(i.hour) + '-' + str(i.minute)
filename = 'search'+ tm + 'ovr' + str(ovr)+'kind'+ kind +'.txt'
a= [1, 2, 3, 4, 5, 10, 20, 25, 30, 40]
t0= time()

fo = open( filename , 'w' )
fo.write(str(a))
fo.write('\n')
fo.write('hidden_layer_sizes=(1851, 400,), activation= tanh, solver= lbfgs,'+
         'alpha= alp,max_iter= 500,learning_rate_init= 0.001,'+
         'verbose= True, early_stopping= True, validation_fraction= 0.3, tol= 0.0001\n')
fo.close()

hscore= 0.0
lowestsc= 0.0
bestA= 0

for i in range(len(a)):
    score, vect, matrix= evaluateModel(a[i])
    fo = open( filename , 'a' )
    fo.write('\n')
    fo.write('For '+ str(a[i])+'\n')
    fo.write('Avg score '+ str(score)+'\n')
    fo.write('Score ' +str(vect)+'\n')
    fo.write('Conf matr'+'\n')
    fo.write(str(matrix))
    fo.write('\n')
    fo.close()
    
    if(score > hscore):
        worstPred= min(vect)
        if(worstPred > lowestsc):
            hscore= score
            lowestsc= worstPred
            bestA= a[i]

fo = open( filename , 'a' )
fo.write('Best a= '+ str(bestA)+'\n')
fo.write('Score = '+ str(hscore)+ '\n')
fo.write('Lowest score pred= '+ str(lowestsc)+'\n')
print('Best a= '+ str(bestA)+'\n')
print('Score = '+ str(hscore)+ '\n')
print('Done in ' + str(time()-t0)) 

Best a= 2

Score = 0.798967148967

Done in 3580.19926738739


In [26]:
#run
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
x= xin
y= yin
ovr= 1
kind= 'regular'
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=0)
for _ in range(ovr):
    x_train,y_train = overSampling(x_train, y_train, kind)
print(x_train.shape)
print(x.shape)
print(itemfreq(yin))
print(itemfreq(y_train))

x_train= normalize(x_train)
x_test= normalize(x_test)

(919, 1850)
(966, 1850)
[[  0  51]
 [  1 183]
 [  2  85]
 [  3 395]
 [  4  86]
 [  5  60]
 [  6 106]]
[[  0 277]
 [  1 136]
 [  2  57]
 [  3 277]
 [  4  62]
 [  5  44]
 [  6  66]]


In [27]:
i = datetime.datetime.now()
tm= str(i.year) + '-' + str(i.month) + '-' + str(i.day) + '_' + str(i.hour) + '-' + str(i.minute)
filename = 'search'+ tm + 'ovr' + str(ovr)+'kind'+ kind +'.txt'
a= [1, 2, 3, 4, 5, 10, 11, 12, 15, 20, 30, 40, 50]
t0= time()

fo = open( filename , 'w' )
fo.write(str(a))
fo.write('\n')
fo.write('hidden_layer_sizes=(1851, 400,), activation= tanh, solver= lbfgs,'+
         'alpha= alp,max_iter= 500,learning_rate_init= 0.001,'+
         'verbose= True, early_stopping= True, validation_fraction= 0.3, tol= 0.0001\n')
fo.close()

hscore= 0.0
lowestsc= 0.0
bestA= 0

for i in range(len(a)):
    score, vect, matrix= evaluateModel(a[i])
    fo = open( filename , 'a' )
    fo.write('\n')
    fo.write('For '+ str(a[i])+'\n')
    fo.write('Avg score '+ str(score)+'\n')
    fo.write('Score ' +str(vect)+'\n')
    fo.write('Conf matr'+'\n')
    fo.write(str(matrix))
    fo.write('\n')
    fo.close()
    
    if(score > hscore):
        worstPred= min(vect)
        if(worstPred > lowestsc):
            hscore= score
            lowestsc= worstPred
            bestA= a[i]

fo = open( filename , 'a' )
fo.write('Best a= '+ str(bestA)+'\n')
fo.write('Score = '+ str(hscore)+ '\n')
fo.write('Lowest score pred= '+ str(lowestsc)+'\n')
print('Best a= '+ str(bestA)+'\n')
print('Score = '+ str(hscore)+ '\n')
print('Done in ' + str(time()-t0)) 

Best a= 1

Score = 0.770223763152

Done in 3217.8591463565826


[[ 0.37031432 -0.05454595 -0.44155552 ...,  0.58973548  0.31735689
   0.23628113]
 [-1.08160906 -0.63766418 -1.27962613 ..., -0.38228522 -1.08551623
  -1.03715872]
 [-0.81148381 -0.97900183 -0.77376367 ..., -0.26741008 -0.75774213
  -1.11382065]
 ..., 
 [ 0.94651168  1.43700004  1.79149133 ...,  0.33404166  0.54468195
   0.70159836]
 [ 0.89841261  0.69474182  0.53639887 ...,  1.3510311   1.43688811
   1.50750492]
 [ 1.0337644   1.11130688  1.3160062  ...,  0.30386132  0.51284001
   0.67668405]]
[  2.67468311e-16  -1.06310801e-17  -1.28056192e-17 ...,   1.69130820e-17
  -3.62423185e-18  -7.12765598e-18]


MLPClassifier(activation='tanh', alpha=1, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=True, epsilon=1e-08,
       hidden_layer_sizes=(1851, 400), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.3,
       verbose=True, warm_start=False)

In [ ]:
#Score on Kaggle achived: 0.82609 