In [6]:
import numpy as np
import matplotlib.pyplot as pl
import pandas as pd 
from sklearn import preprocessing
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import confusion_matrix
from time import time

In [7]:
xin= np.load("./X_train.npy")
yin= np.load("./y_train.npy")
xout= np.load("./X_test.npy")

In [8]:
def svmPredict(model,xin,yin):
    ypredict= model.predict(xin)
    score= f1_score(yin , ypredict, average='weighted')
    print(confusion_matrix(yin, ypredict))
    print(f1_score(yin, ypredict, average=None))
    return score

nn = MLPClassifier(hidden_layer_sizes=(1851, 150),
                   activation='logistic', 
                   solver='lbfgs', 
                   alpha=2, 
                   verbose=True,
                   learning_rate_init=0.001,
                   max_iter= 2000
                  )

skf = StratifiedKFold(n_splits=5)

for train, test in skf.split(xin, yin):
    nn.fit(xin[train],yin[train])
    svmPredict(nn, xin[test], yin[test])
    

[[ 6  2  0  2  0  0  1]
 [ 0 31  2  0  0  2  2]
 [ 0  1 14  1  1  0  0]
 [ 1  2  2 70  2  1  1]
 [ 0  0  0  1 14  2  1]
 [ 0  1  0  1  1  9  0]
 [ 0  0  0  4  0  0 18]]
[ 0.66666667  0.83783784  0.8         0.88607595  0.77777778  0.69230769
  0.8       ]
[[ 9  1  0  0  0  0  0]
 [ 1 32  1  3  0  0  0]
 [ 0  2 12  3  0  0  0]
 [ 1  1  4 70  1  0  2]
 [ 0  1  2  1 11  0  2]
 [ 0  0  0  1  0 10  1]
 [ 0  1  1  0  0  0 19]]
[ 0.85714286  0.85333333  0.64864865  0.89171975  0.75862069  0.90909091
  0.84444444]
[[ 7  1  1  1  0  0  0]
 [ 1 33  0  1  0  1  1]
 [ 0  2 12  3  0  0  0]
 [ 0  1  1 77  0  0  0]
 [ 0  0  0  3 11  1  2]
 [ 0  1  0  3  3  5  0]
 [ 0  2  0  1  4  0 14]]
[ 0.77777778  0.85714286  0.77419355  0.91666667  0.62857143  0.52631579
  0.73684211]
[[ 5  3  1  1  0  0  0]
 [ 1 29  0  5  1  0  0]
 [ 0  1 16  0  0  0  0]
 [ 0  0  1 72  3  0  3]
 [ 0  0  0  1 14  0  2]
 [ 0  0  0  0  1 11  0]
 [ 0  0  2  2  1  0 16]]
[ 0.625       0.84057971  0.86486486  0.9         0.75675676  0